### PR TITLE
changed logic

### PR DESCRIPTION
**Pull request by Pari-singh**
New logic with threshold setting lesser values to 0

### CODE REVIEW

**Comment by kgao** [comment]
@harish-cu  Please double check and deploy to kafka ec-2 for dashboard to use.

**Comment by kgao** [comment]
@Pari-singh seems like users are not happy with new logic output from our tests, so plz consider to modify this or close the pr.

**Comment by Pari-singh** [comment]
I have done some modifications, @kgao could you check now?

**Comment by harish-cu** [comment]
Let's stick with the current logic for now

**Pull request closed without merging**
