### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by kgao**
Wrap 1.0

### CODE REVIEW

**Comment by clankjak** [comment]
node and npm might be set up differently / incorrectly for me since I rarely use it, but I'm getting two errors when I run ```SET DEBUG=dashboard:* & npm start```:

First error:
```-bash: SET: command not found```

Second error:
```Cannot find module '../config.json'```

**Comment by kgao** [comment]
> node and npm might be set up differently / incorrectly for me since I rarely use it, but I'm getting two errors when I run `SET DEBUG=dashboard:* & npm start`:
> 
> First error:
> `-bash: SET: command not found`
> 
> Second error:
> `Cannot find module '../config.json'`
1. Are you using mac book? If so, u can simply run: "npm install"  then "npm start"
2. Right, you don't have config.json in a public repo(Since there is production Key to use our model) You need to modify the config_template.json (Fill in the url and keys and change the name to config.json, you can request from me based on ur need from slack private channel).  :P

**Comment by kgao** [comment]
Review instruction on calling Model API in another module (kafka consumer) from the ticket here:
https://toydemoproject.atlassian.net/jira/software/projects/PD/boards/14?selectedIssue=PD-23

**Review by clankjak — APPROVED** [review]
Looks good to me! Minor changes, I'd remove debug.log from the commit (and add to .gitignore), and note in the README that you can access the dashboard from localhost:3000 if running in debug/local mode.

I'm not well-versed at all in frontend engineering beyond the basic fundamentals of javascript, but `app.js` and `index.js` look reasonable to me, and the styling looks good as well. We'll probably end up cutting a lot of the extra views below the seat map. Otherwise, the only major change, like we discussed at end of class yesterday, is that we'll have the consumer microservice cache the latest data required for the visualizations in the dashboard.

**Comment by kgao** [comment]
@clankjak Yep, that seat map logic is here:  https://github.com/columbia-dsi/people_detection/commit/e2d28da1ccb7711357ab85df501e971dbf2464cd
We decided to embedded that part to consumer pipeline, once that is integrated, then we could use this to replace the seat map dump in dashboard UI for our MVP.

**Pull request merged**
